//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.NotasEstudiante = new HashSet<NotasEstudiante>();
            this.Docente = new HashSet<Docente>();
        }
    
        public int Id { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public short Credito { get; set; }
        public int DepartamentoId { get; set; }
    
        public virtual ICollection<NotasEstudiante> NotasEstudiante { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<Docente> Docente { get; set; }
    }
}
