//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante : Personas
    {
        public Estudiante()
        {
            this.Nota = new HashSet<NotasEstudiante>();
        }
    
        public int Matricula { get; set; }
        public string PerodoIngreso { get; set; }
    
        public virtual ICollection<NotasEstudiante> Nota { get; set; }
    }
}
